---

- name: mail standalone | set mailname
  debconf:
    name: 'exim4-config'
    question: 'exim4/mailname'
    value: '{{ inventory_hostname }}'
    vtype: string

- name: mail standalone | set config type
  debconf:
    name: 'exim4-config'
    question: 'exim4/dc_eximconfig_configtype'
    value: 'internet site; mail is sent and received directly using SMTP'
    vtype: string

- name: mail standalone | reconfigure package exim4-config
  command: dpkg-reconfigure -fnoninteractive exim4-config